### ISSUE TITLE
Consumer/ Provider API: Search Operation

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#20]
DDC questioned whether the NRLS should support the Provider API: Read Operation? Suggestion that the Consumer API search interaction could be used by both providers and consumer roles. The Provider search could support combination of ODS code + NHS# params. Needs further discussion.

**Comment by wilkinsm** [comment]
Provider and Consumer search capabilities will be the same.

**Comment by swk003** [comment]
This makes sense, but haven't been involved in discussions so can you provide justification and more detail backing the decision made?

**Comment by wilkinsm** [comment]
The NRLS has a single search functionality. In order to provide this functionality under 2 different roles (provider/consumer) with differing rules and requirements (mandatory custodian vs mandatory subject) 
 would require additional role based logic to enforce those rules.

At this stage the additional complexity could be a barrier.

One single rule in this regard can exist of 'either custodian or subject MUST be provided'. It would be up to the provider/consumer to utilise the NRLS as expected and agreed.

**Comment by swk003** [comment]
So from a search perspective nothing has changed i.e. provider/ consumer actors can switch hats as long as they meet agreed NRLS business rule/s? Have you discussed whether the NRLS will support additional search params/combinations or are we sticking with existing custodian (ODS) and patient (NHS#) searches as per NRLS 2.1.0-alpha.1?

**Comment by wilkinsm** [comment]
Yes you could say nothing has changed other than to describe that we have one 'search hat' that both providers and consumers can wear as long as they meet agreed NRLS business rules.

The discussions have resulted in the current proposal to require at least custodian (ODS) or subject (NHS#), but both can be specified together. Without at least one would result in the entire contents of NRLS pointers.

It has been discussed that additional search parameters (created, type etc) could (and probably will) exist in the future but at this stage they most likely will not feature in the spec due to additional complexity and the need for requirement validation on the part of 'created' and then 'type' due to the fact that we are only dealing with one type at this stage . Except for _count which is in aid of pagination (see #24 ). A new issue for created param has been opened - see #34 .

**Comment by wilkinsm** [comment]
Bringing the provider and consumer search spec details inline has been completed and reviewed. This can now be closed.

**Comment by wilkinsm** [comment]
Updates released, now closing ticket.
