### ISSUE TITLE
_format parameter + Accept header

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#42]
Do we also expect to handle formats specified via query parameters (eg ?_format=application/fhir+xml) and what do we do about getting both with different values?

“All requests SHALL contain a valid ‘Authorization’ header and SHALL contain an ‘Accept’ header with at least one of the following application/json+fhir or application/xml+fhir.” I don’t know why we need either header to request this resource. It’s not a secret, and if they don’t tell us what mime type they prefer, we can just pick one?

**Comment by DamianJMurphy** [comment]
Some FHIR clients will expect to be able to use _format. If that and Accept differ, then http://hl7.org/implement/standards/fhir/http.html#mime-type implies in

"This parameter allows a client to override the accept header value when it is unable to set it correctly due to internal limitations"

that  where present _format takes precedence over whatever Accept says.

**Comment by DamianJMurphy** [comment]
Why not just do what https://www.w3.org/Protocols/rfc2616/rfc2616-sec12.html#sec12 says (as referenced by the STU3 FHIR section 2.21.0.6) and return HTTP 406 Not Acceptable if the requestor asks for something the NRLS interface is specified to do ?
